name: build-website

on:
  workflow_call:

jobs:
  build-database:
    name: Build database
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Prepare MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Build database project
      working-directory: ./src/ToyCompany/ToyCompany.Database
      run: MSBuild.exe ToyCompany.Database.sqlproj -property:Configuration=Release

    - name: Upload website as workflow artifact
      uses: actions/upload-artifact@v2
      with:
        name: database
        path: ./src/ToyCompany/ToyCompany.Database/bin/Release/ToyCompany.Database.dacpac
