name: deploy-toy-website-end-to-end
concurrency: toy-company

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:

  # Build the application and database.
  build:
    uses: ./.github/workflows/build.yml
